Sleep 3
Type "vim "
Sleep 500ms
Enter
Escape
Type "[I"
Escape
Type "[2;2R"
Escape
Type "[3;1R"
Escape
Type "[>84;0;0c"
Sleep 500ms
Type ":Terrad"
Tab
Sleep 500ms
Type " "
Sleep 500ms
Type "splunk-terraform signalfx"
Sleep 500ms
Enter
Sleep 5s
Ctrl+C
Sleep 500ms
Type ":Terr"
Tab
Sleep 500ms
Type " "
Sleep 500ms
Type "hashicorp google"
Sleep 500ms
Enter
Sleep 3
Type "website/docs/r/bigquery_table"
Sleep 500ms
Enter
Sleep 500ms
Ctrl+D
Ctrl+D
Ctrl+D
Sleep 1s
Type ":q"
Sleep 500ms
Enter
